-- insert into CRM_LOCATION (Name, Description) values ('Copenhagen', 'Capital of Denmark');
-- insert into CRM_LOCATION (Name, Description) values ('Oslo', 'Capital of Norway');
-- insert into CRM_LOCATION (Name, Description) values ('Stockholm', 'Capital of Sweeden');
